name: Create Release

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: write

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Move contents to XXMITools folder
      run: |
        mkdir XXMITools
        shopt -s extglob
        mv !(XXMITools) XXMITools

    - name: Create zip of repository
      run: zip -r XXMITools_v${{ github.ref_name }}.zip XXMITools

    - name: Create Release
      uses: softprops/action-gh-release@v1
      with:
        files: XXMITools_v${{ github.ref_name }}.zip
        name: Release ${{ github.ref_name }}
        body: |
          See the [changelog](https://github.com/${{ github.repository }}/commits/${{ github.ref_name }}) for details.
        draft: false
        prerelease: false
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}